easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
        - username
        - email
        - enabled
        - lastLogin
        # if administrators are allowed to edit users' passwords and roles, add this:
        - { property: 'plainPassword', type: 'text', type_options: { required: false } }
        - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

    Article:
      class: App\Entity\Article

      list:
        fields:
        - { property: 'image', type: 'image', base_path: '%app.path.images%' }
        # ...
      show:
        fields:
        - { property: 'image', type: 'image', base_path: '%app.path.images%' }


      form:
        fields:
        - title
        - { property: 'content', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
        - { property: 'imageFile', type: 'vich_image' }

    Heading:
      class: App\Entity\Heading


    Presse:
      class: App\Entity\Presse

      list:
        fields:
        - { property: 'image', type: 'image', base_path: '%app.path.images%' }
        # ...
      show:
        fields:
        - { property: 'image', type: 'image', base_path: '%app.path.images%' }


      form:
        fields:
        - title
        - { property: 'imageFile', type: 'vich_image' }

    Partner:
      class: App\Entity\Partner
      list:
        fields:
        - name
        - { property: 'image', type: 'image', base_path: '%app.path.images%' }
        # ...
      show:
        fields:
        - name
        - { property: 'image', type: 'image', base_path: '%app.path.images%' }


      form:
        fields:
        - name
        - position
        - { property: 'imageFile', type: 'vich_image' }
