vich_uploader:
    db_driver: orm



    mappings:
        images:
            uri_prefix: uploads/images/
            upload_destination: '%kernel.root_dir%/../public/uploads/images'

        documents:
          uri_prefix: uploads/documents/
          upload_destination: '%kernel.root_dir%/../public/uploads/documents'
